FROM mcr.microsoft.com/playwright:v1.16.2-focal
USER root
RUN mkdir /tests
COPY . /tests
WORKDIR /tests
RUN npm install
RUN npx @playwright/test install
RUN npx playwright install-deps
CMD ["npx", "playwright", "test"]
